service: search-ninja-api-gateway

plugins:
    - serverless-dotenv-plugin
    - serverless-domain-manager
    - serverless-webpack

provider:
    name: aws
    stage: ${env:STAGE}
    runtime: nodejs12.x
    profile: ${env:AWS_PROFILE}
    stackName: search-ninja-api-gateway-${env:STAGE}

custom:
    customDomain:
        domainName: ${env:DOMAIN_NAME}
        certificateName: ${env:CERTIFICATE_NAME}
        basePath: ''
        stage: ${env:STAGE}
        createRoute53Record: true

functions:
    authorizer:
        name: search-ninja-api-gateway-authorizer-${env:STAGE}
        handler: src/handler.authenticate
        events:
            - http: GET /check-login

resources:
    Resources:
        ApiGatewayRestApi:
            Type: AWS::ApiGateway::RestApi
            Properties:
                Name: search-ninja-api-gateway-${env:STAGE}

        Authorizer:
            Type: AWS::ApiGateway::Authorizer
            Properties:
                AuthorizerResultTtlInSeconds: 300
                AuthorizerUri:
                    Fn::Join:
                        - ''
                        - - 'arn:aws:apigateway:'
                          - !Ref AWS::Region
                          - ':lambda:path/2015-03-31/functions/'
                          - !GetAtt AuthorizerLambdaFunction.Arn
                          - '/invocations'
                Type: 'TOKEN'
                IdentitySource: 'method.request.header.Authorization'
                IdentityValidationExpression: 'Bearer .+'
                Name: search-ninja-default-authorizer-${env:STAGE}
                RestApiId: !Ref ApiGatewayRestApi

        AuthorizerPermission:
            Type: 'AWS::Lambda::Permission'
            Properties:
                Action: lambda:InvokeFunction
                FunctionName: !GetAtt AuthorizerLambdaFunction.Arn
                Principal: apigateway.amazonaws.com

    Outputs:
        ApiGatewayRestApiId:
            Value: !Ref ApiGatewayRestApi
            Export:
                Name: search-ninja-api-gateway-rest-api-id
        ApiGatewayRestApiRootResourceId:
            Value: !GetAtt ApiGatewayRestApi.RootResourceId
            Export:
                Name: search-ninja-api-gateway-root-resource-id
        ApiGatewayAuthorizerId:
            Value: !Ref Authorizer
            Export:
                Name: search-ninja-api-gateway-authorizer-id
